- name: Setting Up Domain Controller
  hosts: domaincontrollers
  gather_facts: yes

  vars:
    ansible_user: Administrator

    vars_files:
      - ./vars/pirate_vars.yml

    tasks:
      - name: Change hostname to {{ server_hostname }}
        win_hostname:
          name: "{{ server_hostname }}"
        register: res

      - name: Install Active Directory Domain Services
        win_feature:
          name=AD-Domain-Services
          include_management_tools=yes
          include_sub_features=yes
          state=present
        register: result

      - name: Install Domain {{ ad_domain }}
        microsoft.ad.domain:
          dns_domain_name: "{{ ad_domain }}"
          safe_mode_password: "{{ ansible_password }}"
        register: ad

      - name: Reboot for ADDS
        win_reboot:
          msg: "INstalling AD DS. Rebooting..."
          pre_reboot_delay: 5
        when: ad.reboot_required

- name: Configuring Win10 Workstation
  hosts: workstations
  gather_facts: yes

  vars:
    ansible_user: localadmin

  vars_files:
    - ./vars/pirate_vars.yml

  tasks:
    - name: Join workstation to {{ ad_domain }}
      microsoft.ad.membership
        dns_domain_name: "{{ ad_domain }}"
        hostname: "{{ workstation_hostname }}"
        domain_admin_user: "{{ domain_admin }}"
        domain_admin_password: "{{ ansible_password }}"
        state: domain
        reboot: true
